# Generated by Django 4.2.7 on 2024-01-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_kelompok_buku_jumlah_buku_kelompok_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kelompok',
        ),
    ]
